[package]
name = "test_pub"
version = "0.1.0"
authors = ["Steven Stanfield <stanfield@scarecrowtech.com>"]
edition = "2018"

[dependencies]
romio = { git = "https://github.com/withoutboats/romio" }

[dependencies.futures]
version = "0.3.0-alpha.16"
package = "futures-preview"